/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Artist = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  visible?: boolean;
  displayOrder?: number;
  color?: "#DF597D" | "#254BCC" | "#215946" | "#F5DB36" | "#F8F1E8";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocalizedText;
    credit?: string;
    rightsNote?: string;
    _type: "image";
  };
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocalizedText;
    credit?: string;
    rightsNote?: string;
    _type: "image";
  };
  card?: CardContent;
  socialProfiles?: Array<
    {
      _key: string;
    } & SocialProfile
  >;
  spotifyEmbedVisible?: boolean;
  description: LocalizedText;
  achievements?: Array<
    {
      _key: string;
    } & LocalizedText
  >;
  links?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  spotifyArtistUrl?: string;
};

export type LocalizedText = {
  _type: "localizedText";
  da: string;
  en?: string;
};

export type CardContent = {
  _type: "cardContent";
  title?: LocalizedText;
  body?: LocalizedText;
  readMore?: LocalizedText;
  showSpotify?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text?: InterfaceText;
  brand?: BrandSettings;
  footer?: FooterSettings;
  seo?: SeoSettings;
  intro: LocalizedText;
  contactTitle: LocalizedText;
  contactText?: LocalizedText;
  contactPhone?: string;
  contactEmail: string;
};

export type SeoSettings = {
  _type: "seoSettings";
  title?: LocalizedText;
  description?: LocalizedOptionalText;
  sharingImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocalizedText;
    credit?: string;
    rightsNote?: string;
    _type: "image";
  };
};

export type FooterSettings = {
  _type: "footerSettings";
  companyNumber?: string;
  address?: LocalizedText;
  copyrightName?: string;
  creditLabel?: LocalizedText;
  creditName?: string;
  creditUrl?: string;
  creditLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type BrandSettings = {
  _type: "brandSettings";
  name: string;
  heroLineOne: string;
  heroLineTwo: string;
  logo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  mark?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  tickerMark?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  favicon?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type InterfaceText = {
  _type: "interfaceText";
  skipLink?: LocalizedText;
  navigationLabel?: LocalizedText;
  artistsLink?: LocalizedText;
  contactLink?: LocalizedText;
  languageLabel?: LocalizedText;
  languageAccessibleLabel?: LocalizedText;
  homeAccessibleLabel?: LocalizedText;
  artistsHeading?: LocalizedText;
  artistsSubtitle?: LocalizedText;
  privacyLink?: LocalizedText;
  backToTop?: LocalizedText;
  backToHome?: LocalizedText;
  readMore?: LocalizedText;
  flipCard?: LocalizedText;
  returnToPhoto?: LocalizedText;
  carouselLabel?: LocalizedText;
  carouselInstructions?: LocalizedText;
  puckInstructions?: LocalizedText;
  emptyRoster?: LocalizedText;
  photoCredit?: LocalizedText;
  spotifyLink?: LocalizedText;
  spotifyPlayer?: LocalizedText;
  companyNumberLabel?: LocalizedText;
  responsibleContactLabel?: LocalizedText;
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocalizedText;
  seoTitle?: LocalizedText;
  description?: LocalizedOptionalText;
  sections?: Array<
    {
      _key: string;
    } & PolicySection
  >;
};

export type LocalizedOptionalText = {
  _type: "localizedOptionalText";
  da?: string;
  en?: string;
};

export type PolicySection = {
  _type: "policySection";
  title: LocalizedText;
  kind: "text" | "responsible";
  body?: LocalizedRichText;
};

export type LocalizedRichText = {
  _type: "localizedRichText";
  da?: RichText;
  en?: RichText;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: "bullet" | "number";
  markDefs?: Array<
    | {
        href: string;
        _type: "link";
        _key: string;
      }
    | {
        note?: string;
        _type: "contactEmail";
        _key: string;
      }
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SocialProfile = {
  _type: "socialProfile";
  platform: "Instagram" | "Facebook" | "Website";
  url: string;
  label?: LocalizedText;
  showOnCard?: boolean;
  showInDetails?: boolean;
};

export type ExternalLink = {
  _type: "externalLink";
  label: string;
  url: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Artist
  | LocalizedText
  | CardContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SiteSettings
  | SeoSettings
  | FooterSettings
  | SanityFileAssetReference
  | BrandSettings
  | InterfaceText
  | PrivacyPage
  | LocalizedOptionalText
  | PolicySection
  | LocalizedRichText
  | RichText
  | SocialProfile
  | ExternalLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/lib/content-model.ts
// Variable: SITE_CONTENT_QUERY
// Query: {  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{    intro,contactTitle,contactEmail,contactPhone,text,    brand{...,logo{asset->{url}},mark{asset->{url}},tickerMark{asset->{url}},favicon{asset->{url}}},    footer{...,creditLogo{asset->{url}}},seo{...,sharingImage{...,asset->{url}}}  },  "privacy": *[_type == "privacyPage" && _id == "privacyPage"][0]{title,seoTitle,description,sections},  "artists": *[_type == "artist" && visible == true] | order(displayOrder asc, name asc){    _id,name,"slug":slug.current,description,achievements,spotifyArtistUrl,spotifyEmbedVisible,color,card,    links[]{_key,label,url},socialProfiles[]{_key,label,url,platform,showOnCard,showInDetails},    image{...,asset->{url}},heroImage{...,asset->{url}}  }}
export type SITE_CONTENT_QUERY_RESULT = {
  settings: {
    intro: LocalizedText;
    contactTitle: LocalizedText;
    contactEmail: string;
    contactPhone: string | null;
    text: InterfaceText | null;
    brand: {
      _type: "brandSettings";
      name: string;
      heroLineOne: string;
      heroLineTwo: string;
      logo: {
        asset: {
          url: string;
        } | null;
      } | null;
      mark: {
        asset: {
          url: string;
        } | null;
      } | null;
      tickerMark: {
        asset: {
          url: string;
        } | null;
      } | null;
      favicon: {
        asset: {
          url: string;
        } | null;
      } | null;
    } | null;
    footer: {
      _type: "footerSettings";
      companyNumber?: string;
      address?: LocalizedText;
      copyrightName?: string;
      creditLabel?: LocalizedText;
      creditName?: string;
      creditUrl?: string;
      creditLogo: {
        asset: {
          url: string;
        } | null;
      } | null;
    } | null;
    seo: {
      _type: "seoSettings";
      title?: LocalizedText;
      description?: LocalizedOptionalText;
      sharingImage: {
        asset: {
          url: string;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: LocalizedText;
        credit?: string;
        rightsNote?: string;
        _type: "image";
      } | null;
    } | null;
  } | null;
  privacy: {
    title: LocalizedText;
    seoTitle: LocalizedText | null;
    description: LocalizedOptionalText | null;
    sections: Array<
      {
        _key: string;
      } & PolicySection
    > | null;
  } | null;
  artists: Array<{
    _id: string;
    name: string;
    slug: string;
    description: LocalizedText;
    achievements: Array<
      {
        _key: string;
      } & LocalizedText
    > | null;
    spotifyArtistUrl: string | null;
    spotifyEmbedVisible: boolean | null;
    color: "#215946" | "#254BCC" | "#DF597D" | "#F5DB36" | "#F8F1E8" | null;
    card: CardContent | null;
    links: Array<{
      _key: string;
      label: string;
      url: string;
    }> | null;
    socialProfiles: Array<{
      _key: string;
      label: LocalizedText | null;
      url: string;
      platform: "Facebook" | "Instagram" | "Website";
      showOnCard: boolean | null;
      showInDetails: boolean | null;
    }> | null;
    image: {
      asset: {
        url: string;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: LocalizedText;
      credit?: string;
      rightsNote?: string;
      _type: "image";
    } | null;
    heroImage: {
      asset: {
        url: string;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: LocalizedText;
      credit?: string;
      rightsNote?: string;
      _type: "image";
    } | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    intro,contactTitle,contactEmail,contactPhone,text,\n    brand{...,logo{asset->{url}},mark{asset->{url}},tickerMark{asset->{url}},favicon{asset->{url}}},\n    footer{...,creditLogo{asset->{url}}},seo{...,sharingImage{...,asset->{url}}}\n  },\n  "privacy": *[_type == "privacyPage" && _id == "privacyPage"][0]{title,seoTitle,description,sections},\n  "artists": *[_type == "artist" && visible == true] | order(displayOrder asc, name asc){\n    _id,name,"slug":slug.current,description,achievements,spotifyArtistUrl,spotifyEmbedVisible,color,card,\n    links[]{_key,label,url},socialProfiles[]{_key,label,url,platform,showOnCard,showInDetails},\n    image{...,asset->{url}},heroImage{...,asset->{url}}\n  }\n}': SITE_CONTENT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
